project:
  type: website
  output-dir: C:/Users/pgrieve.stu/OneDrive - UBC/Documents/GitHub/Eportfolio

website:
  title: "Paul's E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: CV/Resume
      - href: work_exp.qmd
        text: Professional Work Experience
      - href: mgem.qmd
        text: Masters of Geomatics for Environmental Management
      - href: publications.qmd
        text: Publications
      

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

