project:
  type: website
  output-dir: C:/Users/pgrieve.stu/OneDrive - UBC/Documents/GitHub/Eportfolio

website:
  title: "Paul's E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: CV/Resume
      - href: publications.qmd
        text: Publications
      - href: content.qmd
        text: Content & Deliverables

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

