project:
  type: website
  output-dir: docs

website:
  title: "Paul's E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: CV/Resume
      - href: work_exp.qmd
        text: Work Experience
      - href: mgem.qmd
        text: MGEM
      - href: hobbies.qmd
        text: Hobbies/Interests
      - href: publications.qmd
        text: Publications
      

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

